### ISSUE TITLE
Caching And Env

### ISSUE THREAD

**Issue by krizzdev** [errorstreamapi/errorstream-laravel#5]
I wasn't able to send my exceptions to the errorstream service.
I noticed, that in the ErrorStreamServiceProvider you make direct acces with the env() method.
like: env('ERROR_STREAM_API_TOKEN');

Since laravel 5.2 it is not recommended to use env() outside from the config files.
"If you are calling env from within your application, it is strongly recommended you add proper configuration values to your configuration files and call env from that location instead, allowing you to convert your env calls to config calls."

So I suggest to use the config() method inside the service provider and make an additional entry in a config file.

Otherwise it don't work for me. 

I will make a pull request.

**Comment by krizzdev** [comment]
#6

**Comment by kevinhamilton** [comment]
Hey Chris,

Thanks for making the pull request. I'll have to check compatibility with Laravel 5.1 before I move forward. If not I think we can switch to publishing some assets.

We have clients using Laravel 5.2 - myself included. I was also able to install and test it on a Laravel 5.2.39 installation. I'll contact you via your support ticket.

**Comment by krizzdev** [comment]
Hey Kevin,

thanks for the quick reply.
Yes, I dunno why env() always return null. Had this a month ago for another
project. I will try to run errorstream-laravel on a fresh install later.

Seems its an dotEnv issue also.
https://github.com/vlucas/phpdotenv/issues/76#issuecomment-167806230

2016-06-28 17:03 GMT+02:00 Kevin Hamilton notifications@github.com:

**Comment by kevinhamilton** [comment]
Interesting read, thanks for linking that issue @ChrisSFR i'll get an update pushed out today.

**Comment by kevinhamilton** [comment]
Merged and available in 2.0 release of errorstream/errorstream-laravel. Should be available to install via composer now.
