### ISSUE TITLE
Don't report in local enviornment

### ISSUE THREAD

**Issue by cmarfil** [errorstreamapi/errorstream-laravel#9]
Hello,

it's possible configure package to don't report to errorstream in local enviornment?

I tried with this without result:

**app/Exceptions/Handler.php**

``` php
    /**
     * Report or log an exception.
     *
     * This is a great spot to send exceptions to Sentry, Bugsnag, etc.
     *
     * @param  \Exception  $e
     * @return void
     */
    public function report(Exception $e)
    {

        if ($this->shouldReport($e) && !config('app.debug')) {
            ErrorStream::reportException($e);
        }

        parent::report($e);
    }
```

Thanks!

**Comment by kevinhamilton** [comment]
Yes, actually it's something I was planning on adding as soon as possible. I'll try to get an update in tonight. Thanks!

**Comment by kevinhamilton** [comment]
Two years later but I did add this in. You can review the docs on github. Just update to 4.0+ and you'll see new flag "enabled". This way you can turn it off for builds, tests, local environment, etc.
